version: "3.7"
volumes:
  pgdata:
  shiny_logs:

services:
  shiny:
    container_name: shiny
    build:
      context: "."
      dockerfile: Dockerfile_R
    restart: always
    user: root
    # Uncomment the lines below to disable application logs STDOUT output
    # environment:
    #   - APPLICATION_LOGS_TO_STDOUT=false
    ports:
        - "80:3838"
    depends_on:
      - postgresql
    volumes:
      - 'shiny_logs:/var/log/shiny-server'
      - './mountpoints/apps:/srv/shiny-server'

  postgresql:
    container_name: postgresql
    build:
      context: "."
      dockerfile: "Dockerfile-postgis"
    env_file:
      - .env_db
    ports:
      - 5432:5432
    volumes:
      - pgdata:/var/lib/postgresql/data
    restart: always

